{% set name = "festvox-kallpc16k" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://festvox.org/packed/festival/2.5/voices/festvox_kallpc16k.tar.gz
  sha256: 809c4ab5ed9e4df4a658b58d5c56fe35055723f00d81a238168f5a1ebdaed08c

build:
  number: 1
  noarch: generic

requirements:
  run:
    - festival
    - festlex-cmu
    - festlex-poslex

test:
  requires:
    - festival
    - festlex-cmu
    - festlex-poslex
  commands:
    - test -f $PREFIX/share/festival/voices/english/kal_diphone/festvox/kal_diphone.scm     # [unix]
    - test -f $PREFIX/share/festival/voices/english/kal_diphone/festvox/kaldurtreeZ.scm     # [unix]
    - test -f $PREFIX/share/festival/voices/english/kal_diphone/group/kallpc16k.group       # [unix]
    - sh -c 'echo "test" | text2wave - 2>&1 | grep -qi error && exit 1 || exit 0'; echo $?  # [unix]

about:
  home: https://github.com/festvox/festival
  summary: 'American English male speaker for festival, 16khz sample rate'
  description: 'American English male speaker for festival, 16khz sample rate'
  license: BSD-4-Clause
  license_family: BSD
  license_file: lib/voices/english/kal_diphone/COPYING
  doc_url: http://festvox.org/dbs/dbs_kal.html
  dev_url: http://festvox.org

extra:
  recipe-maintainers:
    - peci1
